<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE recetas [

<!ELEMENT recetas (receta+)>
<!ELEMENT receta (nombre, ingredientes, preparacion)>
<!ATTLIST receta dificultad CDATA #REQUIRED>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT ingredientes (ingrediente+)>
<!ELEMENT ingrediente (#PCDATA)>
<!ELEMENT preparacion (paso*)>
<!ELEMENT paso (#PCDATA)>

]>


<recetas>
    <!-- Esta receta me la paso Doña Mari el 24/07/1998 en Barcelona -->
    <receta dificultad="facil">
        <nombre>Tostas de Pan</nombre>
        <ingredientes>
            <ingrediente>Pan</ingrediente>
        </ingredientes>
        <preparacion>
            <paso>Calentar sarten y volcar ingrendientes</paso>
            <paso>Dar la vuelta a la tortilla y despues retirar</paso>
        </preparacion>
    </receta>

    <!-- Receta de Juana la Cordobesa del Verano de 2001 en Tarifa -->
    <receta dificultad="media">
        <nombre>Salmorejo</nombre>
        <ingredientes>
            <ingrediente>Tomate</ingrediente>
            <ingrediente>Pan</ingrediente>
            <ingrediente>Ajo</ingrediente>
            <ingrediente>AOVE</ingrediente>
        </ingredientes>
        <preparacion>
            <paso>Trituramos todo en una picadora</paso>
            <paso>Colamos y servimos con jamon y huevo</paso>
        </preparacion>
    </receta>

        <receta dificultad="facil">
        <nombre>Manzana a bocados</nombre>
        <ingredientes>
            <ingrediente>Manzana</ingrediente>
        </ingredientes>
        <preparacion>
        </preparacion>
    </receta>
</recetas>