<?xml version="1.0" encoding="UTF-8"?>


<!DOCTYPE videojuegos [
    <!ELEMENT videojuegos (videojuego+)>

    <!ELEMENT videojuego (titulo, plataforma, genero, desarrolladora, fecha_lanzamiento, pegi, precio, estado)>

    <!ELEMENT titulo (#PCDATA)>
    <!ATTLIST titulo Estado CDATA #REQUIRED > 

    <!ELEMENT plataforma (#PCDATA)>
    <!ELEMENT genero (#PCDATA)>

    <!ELEMENT desarrolladora (nombre, email, web)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT email (#PCDATA)>
    <!ELEMENT web (#PCDATA)>

    <!ELEMENT fecha_lanzamiento (#PCDATA)>
    <!ELEMENT pegi (#PCDATA)>
    <!ELEMENT precio (#PCDATA)>
    <!ELEMENT estado (#PCDATA)>
]>

<videojuegos>

    <videojuego>
        <titulo Estado="agotado">FC 26</titulo>
        <plataforma>PlayStation 5</plataforma>
        <genero>Deportes</genero>
        <desarrolladora>
            <nombre>PlayStation Studios</nombre>
            <email>support@playstation.com</email>
            <web>https://www.playstation.com</web>
        </desarrolladora>
        <fecha_lanzamiento>2025</fecha_lanzamiento>
        <pegi>3</pegi>
        <precio>51.99€</precio>
        <estado>Agotado</estado>
    </videojuego>

    <videojuego>
        <titulo Estado="agotado">Gran Turismo 7</titulo>
        <plataforma>PlayStation 5</plataforma>
        <genero>Carreras</genero>
        <desarrolladora>
            <nombre>PlayStation Studios</nombre>
            <email>support@playstation.com</email>
            <web>https://www.playstation.com</web>
        </desarrolladora>
        <fecha_lanzamiento>2022</fecha_lanzamiento>
        <pegi>12</pegi>
        <precio>51.99€</precio>
        <estado>Disponible</estado>
    </videojuego>

    <videojuego>
        <titulo Estado="agotado">Super Mario Galaxy</titulo>
        <plataforma>Nintendo Switch</plataforma>
        <genero>Aventura</genero>
        <desarrolladora>
            <nombre>Nintendo Studios</nombre>
            <email>support@nintendo.com</email>
            <web>https://www.nintendo.com</web>
        </desarrolladora>
        <fecha_lanzamiento>2025</fecha_lanzamiento>
        <pegi>7</pegi>
        <precio>69.99€</precio>
        <estado>Agotado</estado>
    </videojuego>

</videojuegos>