=== chemodocente/chemo_xml/EJEMPLODTD/DTD/alumnos.dtd
<!ELEMENT alumnos (alumno*)>
<!ELEMENT alumno (nombre, edad, email)>

<!ELEMENT nombre (#PCDATA)>
<!ELEMENT edad (#PCDATA)>
<!ELEMENT email (#PCDATA)>

=== chemodocente/chemo_xml/EJEMPLODTD/alumnos.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE alumnos SYSTEM "DTD/alumnos.dtd">

<alumnos>
    <alumno>
        <nombre>Ana García</nombre>
        <edad>25</edad>
        <email>ana@email.com</email>
    </alumno>

    <alumno>
        <nombre>Pepe Torres</nombre>
        <edad>25</edad>
        <email>petower@email.com</email>
    </alumno>

    <alumno>
        <nombre>Lucía Osorio</nombre>
        <edad>25</edad>
        <email>lorio@email.com</email>
    </alumno>
</alumnos>
